import { Translations } from './types';

export const AR_TRANSLATIONS: Translations = {
  title: 'نظام التحول الرقمي لمكتبة الجاحظ',
  subtitle: 'ثانوية الجاحظ التأهيلية - Lycée Al-Jahid',
  searchPlaceholder: 'ابحث عن كتاب بالعنوان أو الفئة...',
  available: 'متاح',
  borrowed: 'مستعار',
  adminLogin: 'دخول المسؤول',
  username: 'اسم المستخدم',
  password: 'كلمة المرور',
  login: 'تسجيل الدخول',
  logout: 'تسجيل الخروج',
  addBook: 'تسجيل كتاب جديد',
  borrowBook: 'إعارة كتاب',
  returnBook: 'استرجاع كتاب',
  bookId: 'الرمز العددي',
  specialCode: 'الرمز الخاص',
  bookTitle: 'اسم الكتاب',
  category: 'التصنيف',
  owner: 'المالك',
  status: 'الحالة',
  studentName: 'اسم التلميذ',
  classLevel: 'قسم التلميذ',
  studentId: 'رقم التلميذ',
  loanDate: 'تاريخ الإعارة',
  targetReturnDate: 'تاريخ الإرجاع المستهدف',
  overdueAlerts: 'تنبيهات التأخر: يوجد {n} طالب/ة لديه(ها) كتب متأخرة.',
  overdueAlertsNone: 'تنبيهات التأخر: لا يوجد.',
  totalBooks: 'إجمالي الكتب',
  overdue: 'متأخرة',
  lost: 'ضائعة',
  actions: 'الإجراءات',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',
  settings: 'الإعدادات',
  updateCredentials: 'تحديث بيانات الدخول',
  newUsername: 'اسم المستخدم الجديد',
  newPassword: 'كلمة المرور الجديدة',
  confirmDelete: 'تأكيد الحذف',
  confirmDeleteMessage: 'هل أنت متأكد من حذف هذا الكتاب؟ لا يمكن التراجع عن هذا الإجراء.',
  developedBy: 'شعيب آيت باعدي | جميع الحقوق محفوظة.',
  role: 'Baadi Information Studio',
  institution: 'ثانوية الجاحظ التأهيلية',
};

export const EN_TRANSLATIONS: Translations = {
  title: 'Al-Jahiz Library Digital Transformation System',
  subtitle: 'Lycée Al-Jahid - ثانوية الجاحظ التأهيلية',
  searchPlaceholder: 'Search for a book by title or category...',
  available: 'Available',
  borrowed: 'Borrowed',
  adminLogin: 'Admin Login',
  username: 'Username',
  password: 'Password',
  login: 'Login',
  logout: 'Logout',
  addBook: 'Register New Book',
  borrowBook: 'Check-out Book',
  returnBook: 'Check-in Book',
  bookId: 'Numerical ID',
  specialCode: 'Special Code',
  bookTitle: 'Title',
  category: 'Category',
  owner: 'Owner',
  status: 'Status',
  studentName: 'Student Name',
  classLevel: 'Class / Section',
  studentId: 'Student Number',
  loanDate: 'Loan Date',
  targetReturnDate: 'Target Return Date',
  overdueAlerts: 'Overdue Alerts: {n} student(s) have overdue books.',
  overdueAlertsNone: 'Overdue Alerts: None.',
  totalBooks: 'Total Books',
  overdue: 'Overdue',
  lost: 'Lost',
  actions: 'Actions',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  settings: 'Settings',
  updateCredentials: 'Update Credentials',
  newUsername: 'New Username',
  newPassword: 'New Password',
  confirmDelete: 'Confirm Delete',
  confirmDeleteMessage: 'Are you sure you want to delete this book? This action cannot be undone.',
  developedBy: 'Shoaib Ait Baadi | All Rights Reserved.',
  role: 'Baadi Information Studio',
  institution: 'Lycée Al-Jahid',
};
